version: '3.9'

services:

  profiles_app:
    container_name: profiles_app
    image: melodyme/profiles_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db1:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - java_db1
  java_db1:
    container_name: java_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres1
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}